name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202
    
    # dotnet build and publish
    - name: Build project
      run: |
        dotnet build --configuration Release
      
    - name: Publish project
      run: |
        dotnet publish -c Release --runtime linux-x64 -p:PublishSingleFile=true --self-contained false -o ServerMon-Build
        
    # - name: Compress project
    # - uses: montudor/action-zip@v0.1.1
    #   with:
    #     args: zip -qq -r build.zip ServerMon-Build

    - name: Deploy project
      uses: marcodallasanta/ssh-scp-deploy@v1.0.4
      with:
        local: './ServerMon-Build'
        remote: '~/'
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        user: ${{secrets.USER}}
        key: ${{secrets.KEY}}

    - name: Setting up service
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: ./ServerMon-Build/ServerMon --version
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.KEY}}
