name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202

    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Check output
      run: echo ${{ steps.vars.outputs.short_ref }}

    - name: Build project
      run: |
        dotnet build --configuration Release
      
    - name: Publish project
      run: |
        dotnet publish -c Release --runtime linux-x64 -p:PublishSingleFile=true --self-contained false -o ${{ steps.vars.outputs.short_ref }}-build

    - name: Deploy project
      uses: marcodallasanta/ssh-scp-deploy@v1.0.4
      with:
        local: './${{ steps.vars.outputs.short_ref }}-build'
        remote: '~/'
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        user: ${{secrets.USER}}
        key: ${{secrets.KEY}}

    - name: Setting up service
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: ./${{ steps.vars.outputs.short_ref }}-build/ServerMon --version
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.KEY}}
